autoUpdateSettings: true
projectPath: vlocity
manifest:
- OrchestrationPlanDefinition/ve-sample-Use-Flow-in-OM
- OrchestrationItemDefinition/Test-OM-Flow_ve-sample-Use-Flow-in-OM
- Product2/26e1ed65-5197-86d1-2eb6-79fe6e2cf569